SeleniaRoute8_School_MapScripts::
	.byte 0
OC_School_ES_Mechanics1::
	msgbox OC_School_Text_Mechanics1, MSGBOX_SIGN
	end
OC_School_Text_Mechanics1:
	.string "Type Matchups in Selenia:\p"
	.string "Bug resists Fairy and beats it,\n"
	.string "Ice resists Water and Fairy,\p"
	.string "Poison beats Water, while Psychic\n"
	.string "resists Ground, Poison, and Fairy!$"
OC_School_ES_Mechanics2::
	msgbox OC_School_Text_Mechanics2, MSGBOX_SIGN
	end
OC_School_Text_Mechanics2:
	.string "Pokémon Typings unique to Selenia:\p"
	.string "Vulpix/Ninetales is Fire/Psychic,\n"
	.string "Ampharos is Electric/Dragon,\p"
	.string "Voltorb/Electrode is Electric/Grass,\n"
	.string "Slowbro/Slowking is Poison/Psychic,\p"
	.string "Grimer/Muk is Poison/Dark,\n"
	.string "Koffing/Weezing is Poison/Fire,\p"
	.string "Doduo/Dodrio is Ground/Flying,\n"
	.string "Octillery is Water/Rock,\p"
	.string "and Tropius is Grass/Dark!\n"
	.string "Whew! What a mouthful!$"
OC_School_ES_Mechanics3::
	msgbox OC_School_Text_Mechanics3, MSGBOX_SIGN
	end
OC_School_Text_Mechanics3:
	.string "Individual Values/Effort Values:\p"
	.string "For some odd reason, all Pokémon\n"
	.string "native to Selenia have perfect IVs;\p"
	.string "31 in all six stats! And they can\n"
	.string "also max out all of their EVs too!$"
OC_School_ES_Mechanics4::
	msgbox OC_School_Text_Mechanics4, MSGBOX_SIGN
	end
OC_School_Text_Mechanics4:
	.string "Weather Conditions in Battle:\p"
	.string "There are four types of weather:\n"
	.string "Sun, Rain, Snow, and Sandstorm.\p"
	.string "Sun boosts Fire but weakens Water,\n"
	.string "while Rain is opposite, both by 50%.\p"
	.string "Snow boosts Ice types' Defense and\n"
	.string "Sandstorm boosts Rock types' Sp. Def,\p"
	.string "both also by 50%. Snow also\n"
	.string "boosts Ice type moves by 25%.\p"
	.string "Sandstorm does 1/16 max HP damage,\n"
	.string "except to Rock, Ground, and Steel.$"
OC_School_ES_Mechanics5::
	msgbox OC_School_Text_Mechanics5, MSGBOX_SIGN
	end
OC_School_Text_Mechanics5:
	.string "On Abilities, Expanded:\p"
	.string "Boom Box boosts sound moves while\n"
	.string "while also protecting vs them.\p"
	.string "Weather abilities are permanent\n"
	.string "and heal 1/16 max HP while active.\p"
	.string "Sun Soak, Rain Dish, and Ice Body\n"
	.string "heal 1/8 max HP in their weathers.\p"
	.string "Solid Rock and Filter both\n"
	.string "halve super effective damage.\p"
	.string "Solar Power grants a 1.3x boost\n"
	.string "to Electric/Fire/Grass in Sun.\p"
	.string "Gorilla Tactics deals 1.3x damage,\n"
	.string "but Reckless & Iron Fist do 1.25x.\p"
	.string "Suction Cups prevents held items\n"
	.string "from being swapped or taken away.\p"
	.string "Castform's Forecast activates if\n"
	.string "it's holding a weather extender.$"
	//.string "Shellemental makes all types do\n"
	//.string "neutral damage except Fire & Ice.$"
OC_School_ES_Mechanics6::
	msgbox OC_School_Text_Mechanics6, MSGBOX_SIGN
	end
OC_School_Text_Mechanics6:
	.string "Abilities in Selenia, Part 1:\p"
	.string "Loudred/Exploud: Boom Box\n"
	.string "Swablu line: +Cloud Nine\p"
	.string "Zigzagoon/Linoone: Pickup\n"
	.string "Obstagoon: Reckless/Guts\p"
	.string "Togepi line: Super Luck/Serene Grace\n"
	.string "Persian: Fur Coat/Technician\p"
	.string "Ninetales: Drought\n"
	.string "Pelipper: Drizzle\p"
	.string "Mareep/Flaafy: Static/Fluffy\n"
	.string "Ampharos: Thick Fat/Fur Coat\p"
	.string "Wooper line: Unaware/Water Absorb\n"
	.string "Nido K/Q: Serene Grace/Sheer Force\p"
	.string "Venipede line: Swarm/Shed Skin\n"
	.string "Leavanny: Sun Soak/Chlorophyll\p"
	.string "Zubat line: Inner Focus/Infiltrator\n"
	.string "Bellsprout line: +Skill Link\p"
	.string "Onix: Rock Head/Weak Armor\n"
	.string "Steelix: Rock Head/Sheer Force\p"
	.string "Abra/Kadabra: Synchronize/Magic Guard\n"
	.string "Alakazam: Trace/Magic Guard\p"
	.string "Slowpoke family: Regenerator +\n"
	.string "Own Tempo/Quick Draw/Curious Medicine\p"
	.string "Scraggy line: Shed Skin/Intimidate\n"
	.string "Pawniard line: Defiant/Pressure$"
OC_School_ES_Mechanics7::
	msgbox OC_School_Text_Mechanics7, MSGBOX_SIGN
	end
OC_School_Text_Mechanics7:
	.string "Abilities in Selenia, Part 2:\p"
	.string "Houndour line: Solar Power/Unnerve\p"
	.string "Drifloon line: Flash Fire/Unburden\n"
	.string "Sigilyph: Tinted Lens/Magic Guard\p"
	.string "Diglett line: Sand Force/Arena Trap\n"
	.string "Gastly line: Levitate\p"
	.string "Grimer line: Sticky Hold/Regenerator\n"
	.string "Koffing line: Levitate\p"
	.string "Hitmonlee/Hitmonchan/Hitmontop:\n"
	.string "Reckless, Iron Fist, Technician\p"
	.string "Falinks: Battle Armor/Defiant\n"
	.string "Vanilluxe: Snow Warning\p"
	.string "Litwick/Lampent: Infiltrator/Flame Body\n"
	.string "Chandelure: Infiltrator\p"
	.string "Magnezone: Magnet Pull\n"
	.string "Joltik line: Compound Eyes/Unnerve\p"
	.string "Heracross: Moxie/Guts\n"
	.string "Scyther line: Swarm/Technician\p"
	.string "Venonat: Compound Eyes/Tinted Lens\n"
	.string "Venomoth: Shield Dust/Tinted Lens\p"
	.string "Exeggcute line: Sun Soak/Harvest\n"
	.string "Girafarig line: Early Bird/Sap Sipper\p"
	.string "Doduo line: Early Bird/Guts\n"
	.string "Octillery: Suction Cups/Analytic$"
OC_School_ES_Mechanics8::
	msgbox OC_School_Text_Mechanics8, MSGBOX_SIGN
	end
OC_School_Text_Mechanics8:
	.string "Abilities in Selenia, Part 3:\p"
	.string "Tentacool line: Clear Body/Rain Dish\n"
	.string "Corphish line: Shell Armor/Adaptability\p"
	.string "Chinchou line: Water Absorb/Volt Absorb\n"
	.string "Staryu line: Natural Cure/Analytic\p"
	.string "Spheal line: Slush Rush/Ice Body\n"
	.string "Swinub line: Thick Fat/Ice Body\p"
	.string "Axew line: Unnerve/Mold Breaker\n"
	.string "Tropius: Illusion/Levitate\p"
	.string "Tauros: Stamina/Sheer Force\n"
	.string "Miltank: Thick Fat/Intimidate\p"
	.string "Vaporeon: Water Absorb/Hydration\n"
	.string "Jolteon: Volt Absorb/Static\p"
	.string "Flareon: Solar Power/Guts\n"
	.string "Espeon: Synchronize/Magic Bounce\p"
	.string "Umbreon: Synchronize/Unnerve\n"
	.string "Leafeon: Sun Soak/Chlorophyll\p"
	.string "Glaceon: Ice Body/Slush Rush\n"
	.string "Sylveon: Cute Charm/Super Luck\p"
	.string "Porygon/Porygon-2: Trace/Analytic\n"
	.string "Porygon-Z: Adaptability/Analytic\p"
	.string "Omanyte line: Swift Swim/Sand Rush\n"
	.string "Tyrunt line: Strong Jaw/Sand Force\p"
	.string "Lapras: Rain Dish/Filter\n"
	.string "Snorlax: Poison Heal/Thick Fat\p"
	.string "Whew! That was too much info!$"
OC_R8W_ES_Teacher::
	lock
	faceplayer
	msgbox R8W_Text_Teacher, MSGBOX_NPC
	release
	end
R8W_Text_Teacher:
	.string "Hello! Welcome to the\n"
	.string "New Ebonheart Review Center!\p"
	.string "Feel free to browse the blackboards\n"
	.string "to brush up on your battle knowledge!\p"
	.string "And don't worry, you can use your\n"
	.string "phone to take pics of the lessons!$"
OC_R8W_ES_Shadow::
	lock
	faceplayer
	msgbox R8W_Text_Shadow, MSGBOX_NPC
	release
	end
R8W_Text_Shadow:
	.string "I'm keeping an eye on the kid\n"
	.string "in the corner of the room.\p"
	.string "He has his issues, but I can\n"
	.string "tell he has great potential.$"
School_ES_IceBoy::
	lock
	faceplayer
	goto_if_set FLAG_ITEM_SCHOOL_NEVERMELTICE, School_ES_ExplainIce
	msgbox School_Text_IceBoy, MSGBOX_DEFAULT
	giveitem ITEM_NEVER_MELT_ICE
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setflag FLAG_ITEM_SCHOOL_NEVERMELTICE
	release
	end
School_ES_ExplainIce::
	msgbox School_Text_ExplainIce, MSGBOX_DEFAULT
	release
	end
School_Text_IceBoy:
	.string "I love Ice types but I'm\n"
	.string "not really good at battling…\p"
	.string "Here, take this.$"
School_Text_ExplainIce:
	.string "Never-Melt Ice is also known\n"
	.string "as Blue Ice or Stalhrim.\p"
	.string "It's a special kind of ice with\n"
	.string "magical, cryogenic properties.$"
School_ES_Dispenser::
	lock
	msgbox School_Text_Dispenser, MSGBOX_DEFAULT
	giveitem ITEM_FRESH_WATER
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	release
	end
School_Text_Dispenser:
	.string "It may not look like it,\n"
	.string "this is a water fountain!$"
OC_R8W_ES_TVSign::
	msgbox OC_R8W_Text_TVSign, MSGBOX_SIGN
	end
OC_R8W_Text_TVSign:
	.string "The screen has a powerpoint\n"
	.string "on Pokémon battle mechanics!$"
OC_R8W_ES_Henri::
	trainerbattle_single TRAINER_OC_SCHOOL_HENRI, R8W_HenriIntro, R8W_HenriDefeat
	msgbox R8W_HenriPostBattle, MSGBOX_AUTOCLOSE
	end
OC_R8W_ES_Angelo::
	trainerbattle_single TRAINER_OC_SCHOOL_ANGELO, R8W_AngeloIntro, R8W_AngeloDefeat
	msgbox R8W_AngeloPostBattle, MSGBOX_AUTOCLOSE
	end
OC_R8W_ES_Nick::
	trainerbattle_single TRAINER_OC_SCHOOL_NICK, R8W_NickIntro, R8W_NickDefeat
	msgbox R8W_NickPostBattle, MSGBOX_AUTOCLOSE
	end
OC_R8W_ES_Lorenzo::
	trainerbattle_single TRAINER_OC_SCHOOL_LORENZO, R8W_LorenzoIntro, R8W_LorenzoDefeat
	msgbox R8W_LorenzoPostBattle, MSGBOX_AUTOCLOSE
	end
R8W_HenriIntro:
	.string "I'm brushing up on my knowledge\n"
	.string "so I can be a competitive battler!$"
R8W_HenriDefeat:
	.string "Good game, well played!$"
R8W_HenriPostBattle:
	.string "Guess I need to optimize\n"
	.string "my team even further…$"
R8W_AngeloIntro:
	.string "Battling is fun, but I\n"
	.string "also like studying magic!$"
R8W_AngeloDefeat:
	.string "Good work!$"
R8W_AngeloPostBattle:
	.string "Guess I need to review more…$"
R8W_NickIntro:
	.string "Sup? I'm Nick!$"
R8W_NickDefeat:
	.string "Good job!$"
R8W_NickPostBattle:
	.string "Angelo's one of the best\n"
	.string "and brightest minds around!$"
R8W_LorenzoIntro:
	.string "Mm, I could go for some\n"
	.string "chocolate right about now…$"
R8W_LorenzoDefeat:
	.string "Decaffinated!$"
R8W_LorenzoPostBattle:
	.string "My family runs the Safari Zone\n"
	.string "in Agriopolis; you should visit!$"