gText_Birch_Welcome::
	.string "Welcome to the world of Pokémon!\n"
	.string "My name is Maple Moonstone!\p"
	.string "I'm the leading Pokémon Professor\n"
	.string "in the entire nation of Selenia!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited\n"
	.string "by creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon;\p"
	.string "learning alongside them, studying\n"
	.string "things like science and even magic!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Alright!\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Ah, I remember now!\p"
	.string "You're {PLAYER}, my next-door neighbor\n"
	.string "in my hometown of Eastford!\l"
	.string "I forgot! Silly me!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready, {PLAYER}?\p"
	.string "Your very own adventure\n"
	.string "is about to unfold!\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "I'll meet up with\n"
	.string "you at your house!\p"
	.string "$"
