Text_PictureBookShelf:
	.string "There's a set of Pokémon picture books.$"
Text_BookShelf:
	.string "It's filled with all sorts of books.$"
Text_PokemonCenterBookShelf:
	.string "It's filled with plenty of books\n"
	.string "for anyone to pick up and read!$"
Text_Vase:
	.string "A beautiful ceramic pot!\p"
	.string "There's nothing valuable inside,\n"
	.string "so you shouldn't try to break it!$"
Text_EmptyTrashCan:
	.string "It's empty.$"
Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "snacks and Pokémon merchandise.$"
Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
