gText_WouldYouLikeToRestYourPkmn::
	.string "Hey there! Welcome to\n"
	.string "the Pokémon Center!\p"
	.string "We heal up all ya Pokémon to\n"
	.string "tip-top shape, all for free!\p"
	.string "Need any healin'?$"

gText_IllTakeYourPkmn::
	.string "Awright, I'll take your Pokémon\n"
	.string "for a lil' bit. Take it easy!$"

gText_RestoredPkmnToFullHealth::
	.string "Thanks for waitin'!\p"
	.string "All ya Pokémon are\n"
	.string "now fully healed!$"

gText_WeHopeToSeeYouAgain::
	.string "See ya soon!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Awright, I'll take your Pokémon\n"
	.string "for a lil' bit. Take it easy!$"

gText_ThankYouForWaiting::
	.string "Thanks for waitin'!$"

gText_WeHopeToSeeYouAgain2::
	.string "See ya soon!$"
